
import axios from "axios";
// Import serialUtils. Since we are in a script, we might need a relative path or copy the functions if imports fail.
// For robustness in this script context, I will import from the source file.
import { generateSerialNumberRange, getLastSequenceNumber, getModelCode } from "../lib/serialUtils.js";

const BASE_URL = "https://issue-deeper-tests-requires.trycloudflare.com";
const PRODUCT_NAME = "SD8 Controller"; // Matches logic for SD8
const QTY = 20;

const run = async () => {
    try {
        console.log("Starting Verification Batch Creation...");

        // 1. Fetch Batches
        console.log("Fetching existing batches...");
        const batchesRes = await axios.get(`${BASE_URL}/batches`);
        const allBatches = batchesRes.data || [];
        console.log(`Found ${allBatches.length} existing batches.`);

        // 2. Prepare Data
        const batchDate = new Date();
        const batchNo = `BAT-${batchDate.getFullYear()}-${Math.floor(Math.random() * 10000)}`;
        const modelCode = getModelCode(PRODUCT_NAME);

        const yy = batchDate.getFullYear().toString().substring(2);
        const mm = (batchDate.getMonth() + 1).toString().padStart(2, '0');
        const yymm = `${yy}${mm}`;

        const lastSeq = getLastSequenceNumber(allBatches, modelCode, yymm);
        const nextSeq = lastSeq + 1;

        console.log(`Model: ${modelCode}, YYMM: ${yymm}, Last Sequence: ${lastSeq}, Next Sequence: ${nextSeq}`);

        // 3. Generate Serial Number Range
        const productSr = generateSerialNumberRange(PRODUCT_NAME, batchNo, batchDate, nextSeq, QTY);
        console.log(`Generated Serial Range: ${productSr}`);

        // 4. Create Batch Payload
        const payload = {
            batchNo: batchNo,
            requestNo: "VERIFY-AUTO-001",
            checkNo: "CHK-AUTO-001",
            productSr: productSr,
            acceptedQty: QTY,
            status: "Ready", // or whatever valid status
            inspectionId: "QC-AUTO-VERIFY",
            date: batchDate.toISOString(),
            qualityCheck: [{
                id: 1,
                parameters: "Auto Verify",
                specification: "NA",
                observation: "OK",
                remarks: "Generated by verification script"
            }],
            summary: {
                acceptedQuantity: QTY,
                rejectedQuantity: 0,
                holdScrapQuantity: 0,
                comments: "Verification of Serial Number Logic"
            }
        };

        // 5. Submit
        console.log("Submitting new batch...");
        const response = await axios.post(`${BASE_URL}/batches`, payload);

        if (response.status === 200 || response.status === 201) {
            console.log("✅ Batch Created Successfully!");
            console.log("Values:", response.data);
        } else {
            console.error("❌ Failed to create batch. Status:", response.status);
        }

    } catch (error) {
        console.error("❌ Error during verification:", error.message);
        if (error.response) {
            console.error("Response data:", error.response.data);
        }
    }
};

run();
