export const mockEquipmentData = [
    {
        id: 1,
        slNo: "01",
        equipmentName: "Digital Multimeter",
        masterId: "SCAN-DMM-001",
        subDeviceId: "Sub-001",
        serialNumber: "SN-123456",
        manufacturer: "Fluke",
        model: "179",
        frequency: "Annual",
        location: "Production Lab",
        department: "Quality Assurance",
        certificateNo: "CERT-2023-001",
        calibrationSource: "NABL Lab",
        lastCalibration: "2023-08-15", // In form it is lastCalibrationDate
        lastCalibrationDate: "2023-08-15",
        dueDate: "2024-08-15", // In form it is nextDueDate
        nextDueDate: "2024-08-15",
        calibratedBy: "External (NABL Lab)",
        status: "Calibrated",
        remarks: "Handle with care."
    },
    {
        id: 2,
        slNo: "02",
        equipmentName: "Pressure Gauge",
        masterId: "SCAN-PG-045",
        subDeviceId: "Sub-002",
        serialNumber: "SN-789012",
        manufacturer: "Wika",
        model: "PG-100",
        frequency: "6 Months",
        location: "Maintenance Area",
        department: "Maintenance",
        certificateNo: "CERT-2024-002",
        calibrationSource: "Internal Lab",
        lastCalibration: "2024-01-10",
        lastCalibrationDate: "2024-01-10",
        dueDate: "2024-07-10",
        nextDueDate: "2024-07-10",
        calibratedBy: "Internal",
        status: "Due Soon",
        remarks: "Check for zero error."
    },
    {
        id: 3,
        slNo: "03",
        equipmentName: "Temperature Controller",
        masterId: "SCAN-TC-009",
        subDeviceId: "Sub-003",
        serialNumber: "SN-345678",
        manufacturer: "Omron",
        model: "E5CC",
        frequency: "Annual",
        location: "Testing Lab",
        department: "R&D",
        certificateNo: "CERT-2024-003",
        calibrationSource: "External Lab",
        lastCalibration: "2024-02-01",
        lastCalibrationDate: "2024-02-01",
        dueDate: "2024-02-05",
        nextDueDate: "2024-02-05",
        calibratedBy: "External",
        status: "Failed",
        remarks: "Needs repair."
    }
];
